version: '3.7'
services:
  web:
    image: odoo:14.0
    container_name: odoo14c
    depends_on:
      - db
    ports:
      - "8170:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo      
      - ./etc:/etc/odoo
      - ./extra-addons:/mnt/extra-addons  
  db:
    image: postgres:10
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf   
volumes:
  odoo-web-data:
  odoo-db-data:        

